global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'webserver'
    static_configs:
      - targets: ['webserver:80']

  - job_name: 'db'
    static_configs:
      - targets: ['db:3306']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx_prometheus_exporter:9113']
