---
- name: Configure VMware Environment
  hosts: localhost
  gather_facts: no

  vars:
    # Common variables
    vcenter_hostname: "vcenter.local"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "vcenter_password"
    datacenter: "DC1"
    cluster: "Cluster1"
    datastore: "datastore1"
    network: "VM Network"
    vm_template: "centos_template"

    # ESXi hosts settings
    esxi_hosts:
      - name: esxi01
        hostname: esxi01.local
        ip: "192.168.1.11"
        esxi_id: 01
      - name: esxi02
        hostname: esxi02.local
        ip: "192.168.1.12"
        esxi_id: 02

    # VM settings
    app_vms:
      - base_name: "web"
        role: "nginx"
      - base_name: "app"
        role: "flask"
      - base_name: "db"
        role: "mariadb"

  tasks:
    - name: Create VMs for 3-Tier Application on ESXi Hosts
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        cluster: "{{ cluster }}"
        name: "{{ item.0.base_name }}{{ item.1.esxi_id }}"
        template: "{{ vm_template }}"
        power_on: yes
        networks:
          - name: "{{ network }}"
  
