---
- name: Configure VMware Environment
  hosts: localhost
  gather_facts: no

  vars:
    # Common variables
    vcenter_hostname: "vcenter.local"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "vcenter_password"
    datacenter: "DC1"
    cluster: "Cluster1"
    datastore: "datastore1"
    network: "VM Network"
    vm_template: "centos_template"

    # ESXi hosts settings
    esxi_hosts:
      - name: esxi01
        hostname: esxi01.local
        ip: "192.168.1.11"
        esxi_id: 01
      - name: esxi02
        hostname: esxi02.local
        ip: "192.168.1.12"
        esxi_id: 02

    # VM settings
    app_vms:
      - base_name: "web"
        role: "nginx"
      - base_name: "app"
        role: "flask"
      - base_name: "db"
        role: "mariadb"

  tasks:
    - name: Create VMs for 3-Tier Application on ESXi Hosts
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        cluster: "{{ cluster }}"
        name: "{{ app_vm.base_name }}{{ esxi_host.esxi_id }}"
        template: "{{ vm_template }}"
        power_on: yes
        networks:
          - name: "{{ network }}"
            ip: "{{ esxi_host.ip }}"
            netmask: "255.255.255.0"
            gateway: "192.168.1.1"
        disk:
          - size_gb: 20
            type: thin
            datastore: "{{ datastore }}"
        hardware:
          memory_mb: 4096  # 메모리를 4GB로 설정
          num_cpus: 2
      loop: "{{ app_vms | product(esxi_hosts) | list }}"
      loop_control:
        loop_var: "app_vm"
        label: "{{ app_vm.0.base_name }}{{ app_vm.1.esxi_id }}"

    - name: Install and configure Nginx on web server
      when: app_vm.0.role == "nginx"
      community.vmware.vmware_vm_shell:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        vm_id: "{{ app_vm.0.base_name }}{{ app_vm.1.esxi_id }}"
        vm_shell: |
          yum install -y epel-release
          yum install -y nginx
          systemctl start nginx
          systemctl enable nginx
          firewall-cmd --permanent --zone=public --add-service=http
          firewall-cmd --reload
      loop: "{{ app_vms | product(esxi_hosts) | list }}"
      loop_control:
        loop_var: "app_vm"
        label: "{{ app_vm.0.base_name }}{{ app_vm.1.esxi_id }}"

    - name: Install and configure Flask on app server
      when: app_vm.0.role == "flask"
      community.vmware.vmware_vm_shell:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        vm_id: "{{ app_vm.0.base_name }}{{ app_vm.1.esxi_id }}"
        vm_shell: |
          yum install -y python3 python3-pip
          pip3 install Flask
          cat << EOF > /var/www/html/app.py
          from flask import Flask
          app = Flask(__name__)
          @app.route('/')
          def hello():
              return "Hello from Flask!"
          if __name__ == "__main__":
              app.run(host='0.0.0.0')
          EOF
          nohup python3 /var/www/html/app.py &
          firewall-cmd --permanent --zone=public --add-port=5000/tcp
          firewall-cmd --reload
      loop: "{{ app_vms | product(esxi_hosts) | list }}"
      loop_control:
        loop_var: "app_vm"
        label: "{{ app_vm.0.base_name }}{{ app_vm.1.esxi_id }}"

    - name: Install and configure MariaDB on DB server
      when: app_vm.0.role == "mariadb"
      community.vmware.vmware_vm_shell:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        vm_id: "{{ app_vm.0.base_name }}{{ app_vm.1.esxi_id }}"
        vm_shell: |
          yum install -y mariadb-server
          systemctl start mariadb
          systemctl enable mariadb
          mysql_secure_installation
          firewall-cmd --permanent --zone=public --add-service=mysql
          firewall-cmd --reload
      loop: "{{ app_vms | product(esxi_hosts) | list }}"
      loop_control:
        loop_var: "app_vm"
        label: "{{ app_vm.0.base_name }}{{ app_vm.1.esxi_id }}"
