- hosts: all
  become: true
  roles:
    - /opt/MOKONIX/ansible_project/roles/monitoring

  tasks:
    - include: /opt/MOKONIX/ansible_project/playbooks/deploy_containers.yml
    - include: /opt/MOKONIX/ansible_project/playbooks/sync_containers.yml

    - name: Copy init.sql to servers
      copy:
        src: /opt/MOKONIX/ansible_project/roles/db/files/init.sql
        dest: /opt/MOKONIX/ansible_project/init.sql

    - name: Start Docker Compose on servers
      command: docker-compose up -d
      args:
        chdir: /opt/MOKONIX/ansible_project

    - name: Wait for DB containers to be ready
      wait_for:
        port: 3306
        delay: 10
        timeout: 300

    - name: Set up master-master replication on Docker-WEB-WAS-DB-ExMid-1
      shell: docker exec db mysql -uroot -pexample -e "
        CHANGE MASTER TO MASTER_HOST='10.10.2.3', MASTER_USER='exampleuser', MASTER_PASSWORD='examplepass', MASTER_LOG_FILE='mysql-bin.000001', MASTER_LOG_POS=4;
        START SLAVE;"
      when: inventory_hostname == "Docker-WEB-WAS-DB-ExMid-1"

    - name: Set up master-master replication on Docker-WEB-WAS-DB-ExMid-2
      shell: docker exec db mysql -uroot -pexample -e "
        CHANGE MASTER TO MASTER_HOST='10.10.2.2', MASTER_USER='exampleuser', MASTER_PASSWORD='examplepass', MASTER_LOG_FILE='mysql-bin.000001', MASTER_LOG_POS=4;
        START SLAVE;"
      when: inventory_hostname == "Docker-WEB-WAS-DB-ExMid-2"

  post_tasks:
    - name: Run backup script
      shell: /opt/MOKONIX/ansible_project/backup.sh
      when: inventory_hostname == 'primary_host'
