- name: Copy Logstash configuration file
  copy:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf
  notify:
    - Restart Logstash

- name: Ensure Logstash is running
  service:
    name: logstash
    state: started
