- name: Deploy web server container
  hosts:  all
  become: yes

  tasks:
    - name: Ensure the project directory exists on Docker server
      file:
        path: /opt/MOKONIX/ansible_project
        state: directory
        mode: '0755'

    - name: Synchronize role files to Docker server
      synchronize:
        src: "/opt/MOKONIX/ansible_project/roles/{{ item }}/files/"
        dest: "/opt/MOKONIX/ansible_project/{{ item }}/"
        delete: yes
        recursive: yes
        rsync_opts:
          - "--delete"
      with_items:
        - app
        - db
        - monitoring
        - proxyserver
        - webserver

    - name: Install necessary packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Update APT pakage index
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Install Docker Compose
      shell: |
        mkdir -p /usr/local/bin
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

    - name: Run Docker Compose to start the web server
      shell: docker-compose -f /opt/MOKONIX/ansible_project/docker-compose.yml up -d
      args:
        chdir: /opt/MOKONIX/ansible_project

